import { Work_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import NextAuthProvider from '@/provider/NextAuthProvider'

const worksans = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={worksans.className}>
        <NextAuthProvider>

          <Navbar />

          {children}
          <Footer />
        </NextAuthProvider>
      </body>

    </html>
  )
}
